FROM ubuntu:16.04

WORKDIR /app
COPY . /app
RUN apt-get update && apt-get install -y curl wget
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash && apt install -y nodejs
RUN npm install
EXPOSE 8000
EXPOSE 5000

ENTRYPOINT FRONT_URL=http://localhost:5000 npm start
